version: "3.9"

services:
  web:
    build: ./PolygonMigration
    container_name: django_app
    # command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./PolygonMigration:/app
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
    - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
